CREATE DATABASE IF NOT EXISTS BattleCall_v0;

USE BattleCall_v0;

CREATE TABLE IF NOT EXISTS users (id VARCHAR(36) PRIMARY KEY, creationdate DATETIME NOT NULL, username VARCHAR(53) NOT NULL, email VARCHAR(80) NOT NULL, password VARCHAR(90) NOT NULL);
CREATE TABLE IF NOT EXISTS alerts (id VARCHAR(36) PRIMARY KEY, creatorID VARCHAR(36) NOT NULL, gameID VARCHAR(36) NOT NULL, properties VARCHAR(1024));
CREATE TABLE IF NOT EXISTS games (id VARCHAR(36) PRIMARY KEY, gamename VARCHAR(53), propertieslist VARCHAR(1024));