CREATE DATABASE IF NOT EXIST BattleCall_v0.1;

USE BattleCall_v0;

CREATE TABLE users (id VARCHAR(36) PRIMARY KEY, creationdate DATETIME NOT NULL, username VARCHAR(53) NOT NULL, email VARCHAR(80) NOT NULL, password VARCHAR(90) NOT NULL);